# fly.toml app configuration file generated for helloretro on 2024-03-18T16:31:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helloretro'
primary_region = 'sjc'

[build]
dockerfile = "Dockerfile"

[build.args]
PB_VERSION = "0.25.0"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
protocol = "tcp"
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "pb_data"
destination = "/var/pb_data"
initial_size = "1gb"
