version: 3

tasks:
  fmt:
    cmds:
    - deno fmt .
    - deno lint src/ pb_hooks/
  server: pocketbase serve --publicDir dist/ --dev
  build: yarn run build --watch
  default:
    cmds:
    - task: fmt